name: test

inputs:
  test:
    description: abc
    default: '["abc", "eee"]'

  req:
    descriptions: test req
    default: "jup"
    required: true

env:
  def: 'abc'

runs:
  using: composite
    
  steps:

    - name: echoooo
      shell: bash
      run: |
        echo ${{env.def}}

    - name: echoooo
      shell: python
      run: |
        import sys

        sys.exit(2222)
