name: test

inputs:
  test:
    description: abc
    default: '["abc", "eee"]'

env:
  def: 'abc'

runs:
  using: composite
  env:
    arr: ${{ fromJson(inputs.test) }}
    
  steps:
    - name: echoooo
      shell: bash
      run: |
        t=${{ fromJson(inputs.test) }}
        echo "${t[0]}"
        echo "${{env.arr}}
        echo "${{env.arr[0}}
