name: test

inputs:
  test:
    description: abc
    default: ${{ env.def }}

env:
  def: 'abc'

runs:
  using: composite
  steps:
    - name: echoooo
      shell: bash
      run: echo ${{ inputs.test }}
