name: test

inputs:
  test:
    description: abc
    default: '["abc", "eee"]'

env:
  def: 'abc'

runs:
  using: composite
    
  steps:
    - name: echoooo
      shell: bash
      run: |
        echo "${{inputs.test}}" | jq -r '.'
