name: test

inputs:
  test:
    description: abc
    default: '["abc", "eee"]'

env:
  def: 'abc'

runs:
  using: composite
    
  steps:
    - name: echoooo
      shell: bash
      run: |
        INPUT_ARRAY=${{ inputs.test }}
        echo "$INPUT_ARRAY" | jq -r '.[]'
