name: test

inputs:
  test:
    description: abc
    default: '["abc", "eee"]'

env:
  def: 'abc'

runs:
  using: composite
  steps:
    - name: echoooo
      shell: bash
      run: |
        t = ${{ fromJson(inputs.test) }}
        echo ${t[0]}
