name: test

inputs:
  test:
    description: abc
    default: '["abc", "eee"]'

env:
  def: 'abc'

runs:
  using: composite
    
  steps:
    - name: echoooo
      shell: bash
      run: |
        
        t=${{ fromJson(inputs.test) }}
        echo ${t} | jq '.'
        echo "${t[0]}"
        echo $t
        for item in $t; do
          echo "$item"
        done
