name: test

inputs:
  test:
    description: abc
    default: '["abc", "eee"]'

  req:
    descriptions: test req
    default: "jup"
    required: true

env:
  def: 'abc'

runs:
  using: composite
    
  steps:
    - name: echoooo
      shell: bash
      run: |
        echo ${{ inputs.req }}
        INPUT_ARRAY='${{ inputs.test }}'
        echo "$INPUT_ARRAY" | jq -r '.[]' | while IFS= read -r element; do
          echo "Element: $element"
        done
